name: atomic-tagsoup
version: '0.1.0.0'
author: S. M. Hickman
maintainer: sean@grump.ly
license: BSD3
default-extensions:
- ScopedTypeVariables
- RecordWildCards
- FlexibleContexts
- NoMonomorphismRestriction
- MultiParamTypeClasses
- TypeOperators
- DataKinds
- OverloadedStrings
- BangPatterns
- RankNTypes
- TypeFamilies
- DeriveGeneric
- DeriveAnyClass
- FlexibleInstances
- TemplateHaskell
- DeriveDataTypeable
- StandaloneDeriving
- ViewPatterns
- ImplicitParams
- RoleAnnotations
dependencies:
- base >=4.8
- ef-base ==3.0.*
- ef-core ==3.0.*
- atomic ==4.0.*
- lens
- tagsoup
- void
library:
  source-dirs: src
  when:
    - condition: impl(ghcjs -any)
      dependencies:
        - ghcjs-base

